# Generated by Django 6.0 on 2026-01-22 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_AddConversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
                ("balance", models.IntegerField()),
                ("category", models.CharField(max_length=200)),
            ],
        ),
    ]
