# Generated by Django 6.0 on 2026-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="balance",
            field=models.FloatField(),
        ),
    ]
