# Generated by Django 6.0 on 2026-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_transactions_amount_alter_transactions_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.IntegerField(),
        ),
    ]
