# Generated by Django 6.0 on 2026-03-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_transactions_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversations",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
