# Generated by Django 6.0 on 2026-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_conversations_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversations",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
